// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZqaR2dQa5psY0qpSz1Vy70Js83J8YPr0',
    appId: '1:609020159842:web:f20ace6057b889f72a6e3b',
    messagingSenderId: '609020159842',
    projectId: 'social-app-405db',
    authDomain: 'social-app-405db.firebaseapp.com',
    storageBucket: 'social-app-405db.appspot.com',
    measurementId: 'G-Z6PM1JYDC2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBMsnDzYdgZ2OgBTsjuubl7ED5jJ37-hM',
    appId: '1:609020159842:android:e69f28c49b3499f12a6e3b',
    messagingSenderId: '609020159842',
    projectId: 'social-app-405db',
    storageBucket: 'social-app-405db.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAu9QOcNRIn18E9oP2c-tJXnc4asgv_wMA',
    appId: '1:609020159842:ios:c5d93b0cf96cb5742a6e3b',
    messagingSenderId: '609020159842',
    projectId: 'social-app-405db',
    storageBucket: 'social-app-405db.appspot.com',
    iosBundleId: 'com.example.socialApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAu9QOcNRIn18E9oP2c-tJXnc4asgv_wMA',
    appId: '1:609020159842:ios:c5d93b0cf96cb5742a6e3b',
    messagingSenderId: '609020159842',
    projectId: 'social-app-405db',
    storageBucket: 'social-app-405db.appspot.com',
    iosBundleId: 'com.example.socialApp',
  );
}
